### ISSUE TITLE
Honeycomb DSL

### ISSUE THREAD

**Issue by aslakhellesoy** [subsecondtdd/subsecondtdd.org#1]
In a honeycomb architecture there can be many hexagons and adapters, typically 5 for web apps: Test, BrowserApp, HttpApp, WebApp, App.

Assembling these hexagons in different configuration for testing must be easy to write and understand. I propose a simple [TOML](https://github.com/toml-lang/toml)-based DSL for this. Here is an example:

```
title = "Todos"

[memory]
context = todo()
action = todo()
outcome = todo()

[full-stack-electron]
context = todo()
action = domTodo(todo())
outcome = domTodo(todo())

[full-stack-selenium]
context = todo()
action = seleniumTodo(httpTodo(todo()))
outcome = seleniumTodo(httpTodo(todo()))
```

This would be implemented as a plugin for Cucumber. Usage in Cucumber.js:

```javascript
const { setWorldConstructor } = require('cucumber')
const honeycomb = require('honeycomb')

// These factory functions should be memoised (return the same object each time)
const factories = {
  todo: () => {},
  domTodo: () => {},
  seleniumTodo: () => {},
  httpTodo: () => {},
}

const TodoWorld = honeycomb('honeycomb.toml', ,process.env.CUCUMBER_HONEYCOMB, factories)
setWorldConstructor(TodoWorld)
```

Then run with:

```
CUCUMBER_HONEYCOMB=full-stack-electron ./cucumber
```

I think that would be *pretty* neat. /cc @joshski @tooky

**Comment by joshski** [comment]
I made some notes that basically came to the same conclusion. A few other things came to mind:

1. Since proxies always wrap a uniform interface, it might be easier to express a chain of proxies as a list e.g. seleniumTodo, httpTodo, todo

2. Those things start and stop asynchronously so it should support returning `Promise<todo>` or `StartableAndStoppable<todo>`

3. I'm not sure you want an entirely uniform interface for all parts of your proxy chain. For example, I think you might want these two configurations:

```
dom, ajax-client, fake-web-app-host, web-app, todolist
dom, ajax-client, http-web-app-host, web-app, todolist
```
...where http-server-host and fake-server-host are _not_ implementations of the todolist interface. They implement something like `respondToHttpRequest(request, response)`

I'm not sure about the TOML personally. Is it much better than JS?

```js
honeycomb({
  memory: {
    context: 'todo',
    action: 'todo',
    outcome: 'todo'
  },
  'full-stack-electron': {
    context: 'todo',
    action: ['dom', 'todo'],
    outcome: ['dom', 'todo']
  },
  'full-stack-selenium': {
    context: 'todo',
    action: ['selenium', 'http', 'todo'],
    outcome: ['selenium', 'http', 'todo']
  }
})
```

**Comment by aslakhellesoy** [comment]
> Since proxies always wrap a uniform interface, it might be easier to express a chain of proxies as a list e.g. seleniumTodo, httpTodo, todo

That works if they all take a single argument. If some of them needs more (like a baseUrl), we may have to resort to some currying.

> Those things start and stop asynchronously so it should support returning Promise or StartableAndStoppable

Yes, see https://github.com/cucumber-ltd/todo-subsecond/pull/3

Regarding TOML - I realised that shortly after :-) I'll soon push a new PR to the TODO app with an example of that.

**Comment by joshski** [comment]
One other thing: Given that client-heavy web apps tend to be quite similar, can we generalise this pattern so you don't need to configure anything to use it on your project?

**Comment by aslakhellesoy** [comment]
We probably can, I'm just wary of [the wrong abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction) so I'd prefer to use it in anger a bit on different projects first.

**Comment by joshski** [comment]
👍
